version: '3.8'

services:
  shared-storage:
    build: shared-storage
    container_name: shared-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./shared-storage-data:/data # system - container
    image: "shared-storage"

volumes:
  data: {}